### ISSUE TITLE
Add an option to allow nullable fields

### ISSUE THREAD

**Issue by ferdynator** [fsevestre/BooleanFormType#6]
Currently submiting `null` to a `BooleanType` field will result in `false`. This should at least be documented, maybe even add a form option to allow the `Transformer` to also return null. 

I could create a PR if you are interested in this feature

**Comment by omgmashina** [comment]
As far as I know, you cannot do nullable boolean due to the fact that for Symfony false and null are one and the same.
https://github.com/symfony/form/blob/d27a0ee885f37905112c121f60add42f7bd2b0a5/Form.php#L527-L528
But you are right, this should be in README.

**Comment by nebkam** [comment]
@ferdynator I've made a custom type to allow nullable booleans and used it in my APIs for years.
https://gist.github.com/nebkam/716ebdf89d0259cb1aac411ca7d4349f
By convention, it uses `1` for `true`, `-1` for `false` and `0` for `null`, but you can adapt it to your needs.

**Comment by ferdynator** [comment]
@nebkam thanks for the update. I am currently using a similar solution. Symfony does not set `false` values so I am actually transforming `false` to `"0"` client-side (and `true` to `"1"`). That allows me to distinguish true, false and null server-side
